backend:
  name: github
  repo: rozakkj420/grab
  branch: main

media_folder: "img/tenis"
public_folder: "/img/tenis"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Preço", name: "price", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Link HooBuy", name: "link", widget: "string" }
      - { label: "QC Link", name: "qcLink", widget: "string" }
